---
title: "IE 7280 - Project - Topic 1"
date: "8/11/2019"
---

```{r}
library(psych)
library(ggplot2)
library(dplyr)
library(reshape2)
library(GGally)
library(ggpubr)
library(magrittr)
```

```{r}
setwd("/Users/mayankaverma/documents/Advanced Stats/Project - Adv Stats")
data.df<-read.csv("responses.csv", header = TRUE, sep=",")
head(data.df)
nrow(data.df)
```

```{r}
summary_stats<-(data.frame(describe(data.df, na.rm = TRUE, skew=FALSE)))
summary_stats$missing_values<-sapply(data.df, function(x) sum(is.na(x))) 
View(summary_stats)
```

```{r}
#Data Modification
#Data to be analyzed around gender and age, removing the records which does not have gender or age information
data.df<-data.df[!is.na(data.df$Age),]
data.df<-data.df[!is.na(data.df$Gender),]
nrow(data.df)
```

```{r}
#Binning age into categorical variable
data.df$Age_Group<-data.df$Age
data.df$Age_Group<-ifelse((data.df$Age>=15 & data.df$Age<20),"15-20",data.df$Age_Group)
data.df$Age_Group<-ifelse((data.df$Age>=20 & data.df$Age<25),"20-25",data.df$Age_Group)
data.df$Age_Group<-ifelse((data.df$Age>=25 & data.df$Age<=30),"25-30",data.df$Age_Group)
data.df$Age_Group<-as.character(data.df$Age_Group)
class(data.df$Age_Group)
unique(data.df$Age_Group)
```

```{r}
#Analyzing Phobias Across Gender
melted.df<-melt(data.df[!is.na(data.df$Gender),c(64:73,145)],id.vars = "Gender")
colnames(melted.df)[colnames(melted.df)=="variable"] <- "Phobias"
melted.df$Gender<-as.character(melted.df$Gender)
melted.df<-melted.df[melted.df$Gender!="",]

ggplot(melted.df,aes(x=Phobias, y = value, fill = Gender)) +
  geom_boxplot()+ 
  stat_summary(inherit.aes = TRUE,fun.y = mean, geom="point",shape=18, size=5,show_guide = FALSE,aes(color=Gender))+
  theme(plot.title = element_text(size=15, color="blue", face = "italic"), 
        axis.title = element_text(size=10),legend.text=element_text(size=10)) +
  labs(x="Gender",y="Values",title="Box Plot for Phobias Across Gender",fill="Gender")+
  facet_wrap(~Phobias,scales = "free")
```


```{r}
#Analyzing Phobias Across Age Group
melted.df<-melt(data.df[!is.na(data.df$Age_Group),c(64:73,151)],id.vars = "Age_Group")
colnames(melted.df)[colnames(melted.df)=="variable"] <- "Phobias"
melted.df$Gender<-as.character(melted.df$Age_Group)
melted.df<-melted.df[melted.df$Age_Group!="",]

ggplot(melted.df,aes(x=Phobias, y = value, fill =Age_Group)) +
  geom_boxplot()+ 
  stat_summary(inherit.aes = TRUE,fun.y = mean, geom="point",shape=18, size=5,show_guide = FALSE,aes(color=Age_Group))+
  theme(plot.title = element_text(size=15, color="blue", face = "italic"), 
        axis.title = element_text(size=10),legend.text=element_text(size=10)) +
  labs(y="Values",title="Box Plot for Phobias Across Age",fill="Age Group")+
  facet_wrap(~Phobias,scales = "free")

```

```{r}
melted.df<-melt(data.df[!is.na(data.df$Gender),c(64:73,145,151)],id.vars = c("Age_Group","Gender"))
colnames(melted.df)[colnames(melted.df)=="variable"] <- "Phobias"
melted.df
x<-aggregate(value~.,data=melted.df,mean)
x<-x[x$Gender!="",]

Flying<-ggplot(x[x$Phobias=="Flying",], aes(x=Age_Group, y=value, group=Gender)) +
        geom_line(aes(color=Gender))+
        geom_point(aes(color=Gender))+
        labs(y="Mean",x="Age",title="Flying",fill="Gender")+
        theme(plot.title = element_text(size=10, color="blue", face = "italic"), 
        axis.title = element_text(size=4),legend.text=element_text(size=7))

Storm<-ggplot(x[x$Phobias=="Storm",], aes(x=Age_Group, y=value, group=Gender)) +
        geom_line(aes(color=Gender))+
        geom_point(aes(color=Gender))+
        labs(y="Mean",x="Age",title="Storm",fill="Gender")+
        theme(plot.title = element_text(size=10, color="blue", face = "italic"), 
        axis.title = element_text(size=4),legend.text=element_text(size=7))

Darkness<-ggplot(x[x$Phobias=="Darkness",], aes(x=Age_Group, y=value, group=Gender)) +
          geom_line(aes(color=Gender))+
          geom_point(aes(color=Gender))+
          labs(y="Mean",x="Age",title="Darkness",fill="Gender")+
          theme(plot.title = element_text(size=10, color="blue", face = "italic"), 
          axis.title = element_text(size=4),legend.text=element_text(size=7))


Heights<-ggplot(x[x$Phobias=="Heights",], aes(x=Age_Group, y=value, group=Gender)) +
        geom_line(aes(color=Gender))+
        geom_point(aes(color=Gender))+
        labs(y="Mean",x="Age",title="Heights",fill="Gender")+
        theme(plot.title = element_text(size=10, color="blue", face = "italic"), 
        axis.title = element_text(size=4),legend.text=element_text(size=7))

Spiders<-ggplot(x[x$Phobias=="Spiders",], aes(x=Age_Group, y=value, group=Gender)) +
        geom_line(aes(color=Gender))+
        geom_point(aes(color=Gender))+
        labs(y="Mean",x="Age",title="Spiders",fill="Gender")+
        theme(plot.title = element_text(size=10, color="blue", face = "italic"), 
        axis.title = element_text(size=4),legend.text=element_text(size=7))

Snakes<-ggplot(x[x$Phobias=="Snakes",], aes(x=Age_Group, y=value, group=Gender)) +
        geom_line(aes(color=Gender))+
        geom_point(aes(color=Gender))+
        labs(y="Mean",x="Age",title="Snakes",fill="Gender")+
        theme(plot.title = element_text(size=10, color="blue", face = "italic"), 
        axis.title = element_text(size=4),legend.text=element_text(size=7))

Rats<-ggplot(x[x$Phobias=="Rats",], aes(x=Age_Group, y=value, group=Gender)) +
      geom_line(aes(color=Gender))+
      geom_point(aes(color=Gender))+
      labs(y="Mean",x="Age",title="Rats",fill="Gender")+
      theme(plot.title = element_text(size=10, color="blue", face = "italic"), 
      axis.title = element_text(size=4),legend.text=element_text(size=7))

Ageing<-ggplot(x[x$Phobias=="Ageing",], aes(x=Age_Group, y=value, group=Gender)) +
        geom_line(aes(color=Gender))+
        geom_point(aes(color=Gender))+
        labs(y="Mean",x="Age",title="Ageing",fill="Gender")+
        theme(plot.title = element_text(size=10, color="blue", face = "italic"), 
        axis.title = element_text(size=4),legend.text=element_text(size=7))

Dangerous.dogs<-ggplot(x[x$Phobias=="Dangerous.dogs",], aes(x=Age_Group, y=value, group=Gender)) +
                geom_line(aes(color=Gender))+
                geom_point(aes(color=Gender))+
                labs(y="Mean",x="Age",title="Dangerous dogs",fill="Gender")+
                theme(plot.title = element_text(size=10, color="blue", face = "italic"), 
                axis.title = element_text(size=4),legend.text=element_text(size=7))

Fear.of.public.speaking<-ggplot(x[x$Phobias=="Fear.of.public.speaking",], aes(x=Age_Group, y=value, group=Gender)) +
                        geom_line(aes(color=Gender))+
                        geom_point(aes(color=Gender))+
                        labs(y="Mean",x="Age",title="Fear of public speaking",fill="Gender")+
                        theme(plot.title = element_text(size=10, color="blue", face = "italic"), 
                        axis.title = element_text(size=4),legend.text=element_text(size=7))

ggarrange(Flying,Storm,Darkness,Heights,Spiders,Snakes,Rats,Ageing,Dangerous.dogs,Fear.of.public.speaking,ncol = 2, nrow = 5)
```

```{r}
#Anova Models

flying.aov1 <- aov(Flying ~ Age_Group + Gender, data = data.df[data.df$Gender!="",])
summary(flying.aov1)
flying.aov2 <- aov(Flying ~ Age_Group + Gender + Age_Group:Gender, data = data.df[data.df$Gender!="",])
summary(flying.aov2)

darkness.aov1 <- aov(Darkness ~ Age_Group + Gender, data = data.df[data.df$Gender!="",])
summary(darkness.aov1)
darkness.aov2 <- aov(Darkness ~ Age_Group + Gender + Age_Group:Gender, data = data.df[data.df$Gender!="",])
summary(darkness.aov2)

Heights.aov1 <- aov(Heights ~ Age_Group + Gender, data = data.df[data.df$Gender!="",])
summary(Heights.aov1)
Heights.aov2 <- aov(Heights ~ Age_Group + Gender + Age_Group:Gender, data = data.df[data.df$Gender!="",])
summary(Heights.aov2)

Spiders.aov1 <- aov(Spiders ~ Age_Group + Gender, data = data.df[data.df$Gender!="",])
summary(Spiders.aov1)
Spiders.aov2 <- aov(Spiders ~ Age_Group + Gender + Age_Group:Gender, data = data.df[data.df$Gender!="",])
summary(Spiders.aov2)

Storm.aov1 <- aov(Storm ~ Age_Group + Gender, data = data.df[data.df$Gender!="",])
summary(Storm.aov1)
Storm.aov2 <- aov(Storm ~ Age_Group + Gender + Age_Group:Gender, data = data.df[data.df$Gender!="",])
summary(Storm.aov2)

Snakes.aov1 <- aov(Snakes ~ Age_Group + Gender, data = data.df[data.df$Gender!="",])
summary(Snakes.aov1)
Snakes.aov2 <- aov(Snakes ~ Age_Group + Gender + Age_Group:Gender, data = data.df[data.df$Gender!="",])
summary(Snakes.aov2)

Rats.aov1 <- aov(Rats ~ Age_Group + Gender, data = data.df[data.df$Gender!="",])
summary(Rats.aov1)
Rats.aov2 <- aov(Rats ~ Age_Group + Gender + Age_Group:Gender, data = data.df[data.df$Gender!="",])
summary(Rats.aov2)

Ageing.aov1 <- aov(Ageing ~ Age_Group + Gender, data = data.df[data.df$Gender!="",])
summary(Ageing.aov1)
Ageing.aov2 <- aov(Ageing ~ Age_Group + Gender + Age_Group:Gender, data = data.df[data.df$Gender!="",])
summary(Ageing.aov2)

Dangerous.dogs.aov1 <- aov(Dangerous.dogs ~ Age_Group + Gender, data = data.df[data.df$Gender!="",])
summary(Dangerous.dogs.aov1)
Dangerous.dogs.aov2 <- aov(Dangerous.dogs ~ Age_Group + Gender + Age_Group:Gender, data = data.df[data.df$Gender!="",])
summary(Dangerous.dogs.aov2)

Fear.of.public.speaking.aov1 <- aov(Fear.of.public.speaking ~ Age_Group + Gender, data = data.df[data.df$Gender!="",])
summary(Fear.of.public.speaking.aov1)
Fear.of.public.speaking.aov2 <- aov(Fear.of.public.speaking ~ Age_Group + Gender + Age_Group:Gender, data = data.df[data.df$Gender!="",])
summary(Fear.of.public.speaking.aov2)

```


```{r}
#Interaction Plots
data.df<-data.df[!is.na(data.df$Gender),]

par(mfrow=c(3,4))

interaction.plot(data.df$Age_Group,data.df$Gender,data.df$Flying,type="b",col=c(2:3),legend=F,xlab="Age",ylab="Mean of fear of flying")

interaction.plot(data.df$Age_Group,data.df$Gender,data.df$Darkness,type="b",col=c(2:3),legend=F,xlab="Age",ylab="Mean of fear of Darkness")

interaction.plot(data.df$Age_Group,data.df$Gender,data.df$Heights,type="b",col=c(2:3),legend = F,xlab="Age",ylab="Mean of fear of heights")

interaction.plot(data.df$Age_Group,data.df$Gender,data.df$Spiders,type="b",col=c(2:3),legend=F,xlab="Age",ylab="Mean of fear of spiders")

interaction.plot(data.df$Age_Group,data.df$Gender,data.df$Storm,type="b",col=c(2:3),legend=F,xlab="Age",ylab="Mean of fear of storm")

interaction.plot(data.df$Age_Group,data.df$Gender,data.df$Snakes,type="b",col=c(2:3),legend=F,xlab="Age",ylab="Mean of fear of snakes")

interaction.plot(data.df$Age_Group,data.df$Gender,data.df$Rats,type="b",col=c(2:3),legend=F,xlab="Age",ylab="Mean of fear of rats")

interaction.plot(data.df$Age_Group,data.df$Gender,data.df$Ageing,type="b",col=c(2:3),legend=F,xlab="Age",ylab="Mean of fear of ageing")

interaction.plot(data.df$Age_Group,data.df$Gender,data.df$Dangerous.dogs,type="b",col=c(2:3),legend=T,xlab="Age",ylab="Mean of fear of dangerous dogs")

interaction.plot(data.df$Age_Group,data.df$Gender,data.df$Fear.of.public.speaking,type="b",col=c(2:3),legend=T,xlab="Age",ylab="mean of fear of public speaking")



```

```{r}
#Tukey's Test

#Flying
t1<-TukeyHSD(flying.aov2)
t1
plot(t1)

#Ageing
t2<-TukeyHSD(Ageing.aov2)
t2
plot(t2)

```